// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjq10auwAfvXfr5nW43IuVpG0F9NZsFW0',
    appId: '1:587224779962:web:50166391204a9acd8b0683',
    messagingSenderId: '587224779962',
    projectId: 'pi8o7i',
    authDomain: 'pi8o7i.firebaseapp.com',
    storageBucket: 'pi8o7i.firebasestorage.app',
    measurementId: 'G-QZVKK8H81Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOnOfmoT-d7FEMxg5Ppb5AlOd-uI_EYCk',
    appId: '1:587224779962:android:f721e1aa79e6822c8b0683',
    messagingSenderId: '587224779962',
    projectId: 'pi8o7i',
    storageBucket: 'pi8o7i.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkgjvUqCGy-NIf91-rFZjmVbZApSXw_Uw',
    appId: '1:587224779962:ios:ece8d386f860f56e8b0683',
    messagingSenderId: '587224779962',
    projectId: 'pi8o7i',
    storageBucket: 'pi8o7i.firebasestorage.app',
    iosBundleId: 'com.example.assignmentPrototypePi8o7i',
  );
}
